-- Databricks notebook source
CREATE TABLE DWUSER.TMP_ALTER_LIST
(
	MAIN_DEAL_SRL BIGINT NOT NULL
)
DISTRIBUTE ON (MAIN_DEAL_SRL);


CREATE TABLE DWUSER.BI_D_MAIN_DEAL_INFO_WORK_01
(
	MAIN_DEAL_SRL BIGINT NOT NULL,
	DEAL_KIND CHARACTER VARYING(1),
	MAIN_DEAL_NM NATIONAL CHARACTER VARYING(2000) NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	TICKET_START_DATE DATE,
	TICKET_END_DATE DATE,
	STATUS_TYPE NATIONAL CHARACTER VARYING(10) NOT NULL,
	PARTNER_SRL BIGINT NOT NULL,
	CATEGORY_SRL BIGINT,
	DEAL_TYPE NATIONAL CHARACTER VARYING(50) NOT NULL,
	DELIVERY_SPOT NATIONAL CHARACTER VARYING(20),
	TAG_SRL BIGINT,
	DEAL_AMOUNT NUMERIC(24,0) NOT NULL,
	DEAL_DISAMOUNT NUMERIC(24,2) NOT NULL,
	DEAL_DISRATE NUMERIC(10,3) NOT NULL,
	ENCOREDEAL_FLAG NATIONAL CHARACTER VARYING(1),
	IS_EXTERNAL_DEAL NATIONAL CHARACTER VARYING(10),
	DELIVERY_TYPE NATIONAL CHARACTER VARYING(30),
	IS_FDIRECT_DELIVERY NATIONAL CHARACTER(1),
	ALWAYS_SALE NATIONAL CHARACTER(1),
	DEAL_FROM NATIONAL CHARACTER VARYING(60) NOT NULL,
	ADULT_TYPE NATIONAL CHARACTER VARYING(10) NOT NULL,
	USE_DIRECT_PIN NATIONAL CHARACTER VARYING(60),
	ONE_MAN_MAX_COUNT INTEGER NOT NULL,
	STOCK_COUNT BIGINT,
	ACTION_FROM NATIONAL CHARACTER VARYING(20),
	CONTENTS_MAKING NATIONAL CHARACTER VARYING(20),
	CD_STATUS_TYPE NATIONAL CHARACTER VARYING(10),
	DEAL_DELIVERY_POLICY NATIONAL CHARACTER VARYING(20),
	DEAL_DELIVERY_AMOUNT NUMERIC(24,0),
	DEAL_DELIVERY_IF_AMOUNT NUMERIC(18,0),
	USER_VIEW_YN CHARACTER VARYING(1),
	LOAD_DT TIMESTAMP
)
DISTRIBUTE ON (MAIN_DEAL_SRL);



CREATE TABLE DWUSER.BI_D_MAIN_DEAL_INFO_WORK_02
(
	MAIN_DEAL_SRL BIGINT NOT NULL,
	EQUAL_PRICE_YN CHARACTER VARYING(1),
	EQUAL_RATE_YN CHARACTER VARYING(1),
	LOW_RATE_YN CHARACTER VARYING(1),
	ONE_MAN_MAX_COUNT_OPTION BIGINT,
	MAX_COUNT BIGINT,
	LOAD_DT TIMESTAMP
)
DISTRIBUTE ON (MAIN_DEAL_SRL);


CREATE TABLE DWUSER.BI_D_MAIN_DEAL_INFO
(
	MAIN_DEAL_SRL BIGINT NOT NULL,
	DEAL_KIND NATIONAL CHARACTER(1) NOT NULL,
	MAIN_DEAL_NM NATIONAL CHARACTER VARYING(500) NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	TICKET_START_DATE DATE,
	TICKET_END_DATE DATE,
	STATUS_TYPE NATIONAL CHARACTER VARYING(10),
	PARTNER_SRL BIGINT,
	CATEGORY_SRL BIGINT,
	DEAL_TYPE NATIONAL CHARACTER VARYING(50),
	DELIVERY_SPOT NATIONAL CHARACTER VARYING(20),
	TAG_SRL BIGINT,
	DEAL_AMOUNT NUMERIC(24,0),
	DEAL_DISAMOUNT NUMERIC(24,2),
	DEAL_DISRATE NUMERIC(10,3),
	ENCOREDEAL_FLAG NATIONAL CHARACTER(1),
	IS_EXTERNAL_DEAL NATIONAL CHARACTER VARYING(10),
	DELIVERY_TYPE NATIONAL CHARACTER VARYING(30),
	IS_FDIRECT_DELIVERY NATIONAL CHARACTER(1),
	ALWAYS_SALE NATIONAL CHARACTER(1),
	DEAL_FROM NATIONAL CHARACTER VARYING(60),
	ADULT_TYPE NATIONAL CHARACTER VARYING(10),
	USE_DIRECT_PIN NATIONAL CHARACTER VARYING(60),
	ONE_MAN_MAX_COUNT BIGINT,
	STOCK_COUNT BIGINT,
	ACTION_FROM NATIONAL CHARACTER VARYING(20),
	CONTENTS_MAKING NATIONAL CHARACTER VARYING(20),
	CD_STATUS_TYPE NATIONAL CHARACTER VARYING(10),
	EQUAL_PRICE_YN CHARACTER VARYING(1),
	EQUAL_RATE_YN CHARACTER VARYING(1),
	LOW_RATE_YN CHARACTER VARYING(1),
	ONE_MAN_MAX_COUNT_OPTION BIGINT,
	MAX_COUNT BIGINT,
	DEAL_DELIVERY_POLICY NATIONAL CHARACTER VARYING(20),
	DEAL_DELIVERY_AMOUNT NUMERIC(24,0),
	DEAL_DELIVERY_IF_AMOUNT NUMERIC(18,0),
	USER_VIEW_YN CHARACTER VARYING(1),
	LOAD_DT TIMESTAMP
)
DISTRIBUTE ON (MAIN_DEAL_SRL);

COMMENT ON TABLE BI_D_MAIN_DEAL_INFO IS '딜정보(딜정보 마스터 생산용)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.MAIN_DEAL_SRL IS '메인딜번호';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_KIND IS '딜종류구분';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.MAIN_DEAL_NM IS '메인딜명';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.START_DATE IS '시작일시';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.END_DATE IS '종료일시';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.TICKET_START_DATE IS '티켓시작일시';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.TICKET_END_DATE IS '티켓종료일시';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.STATUS_TYPE IS '상태유형';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.PARTNER_SRL IS '파트너번호';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.CATEGORY_SRL IS '카테고리번호';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_TYPE IS '딜유형';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DELIVERY_SPOT IS '딜배송형태(TMON4 : 3PL)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.TAG_SRL IS '컨셉카테고리번호';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_AMOUNT IS '딜정상가격(딜공급원가)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_DISAMOUNT IS '딜할인가격(딜판매가)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_DISRATE IS '할인 비율';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.ENCOREDEAL_FLAG IS 'encoredeal_flag';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.IS_EXTERNAL_DEAL IS '외부연동딜여부';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DELIVERY_TYPE IS '배송유형';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.IS_FDIRECT_DELIVERY IS '해외직배송여부';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.ALWAYS_SALE IS '상시판매';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_FROM IS '딜 최초 등록한 곳';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.ADULT_TYPE IS '성인 인증 유형';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.USE_DIRECT_PIN IS '핀 연동 구분값';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.ONE_MAN_MAX_COUNT IS '1인_최대구매수량';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.STOCK_COUNT IS '재고수량';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.ACTION_FROM IS 'deal_from = partner_deal 인경우 spc/admin 구분';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.CONTENTS_MAKING IS '딜컨텐츠 제작';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.CD_STATUS_TYPE IS '컨텐츠 상태(WT:수정요청전,AV:수정요청,DN:수정완료)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.EQUAL_PRICE_YN IS '옵션가격동일여부(상태값구분안함)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.EQUAL_RATE_YN IS '옵션수수료율동일여부(status = AV,is_option_display = Y 일때)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.LOW_RATE_YN IS '3.3미만 옵션수수료 존재여부';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.ONE_MAN_MAX_COUNT_OPTION IS '인당구매제한(메인옵션기준)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.MAX_COUNT IS '최대 수량(메인옵션기준)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_DELIVERY_POLICY IS '배송정책(딜테이블기준)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_DELIVERY_AMOUNT IS '배송금액(딜테이블기준)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.DEAL_DELIVERY_IF_AMOUNT IS '무료배송조건금액(딜테이블기준)';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.USER_VIEW_YN IS '유저뷰 딜 노출여부';
COMMENT ON COLUMN BI_D_MAIN_DEAL_INFO.LOAD_DT IS '적재일자';










-- COMMAND ----------

CREATE TABLE tmon_netezza.mart.TMP_ALTER_LIST
(
	MAIN_DEAL_SRL BIGINT NOT NULL
);


CREATE TABLE tmon_netezza.mart.BI_D_MAIN_DEAL_INFO_WORK_01
(
	MAIN_DEAL_SRL BIGINT NOT NULL,
	DEAL_KIND STRING,
	MAIN_DEAL_NM STRING NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	TICKET_START_DATE DATE,
	TICKET_END_DATE DATE,
	STATUS_TYPE STRING NOT NULL,
	PARTNER_SRL BIGINT NOT NULL,
	CATEGORY_SRL BIGINT,
	DEAL_TYPE STRING NOT NULL,
	DELIVERY_SPOT STRING,
	TAG_SRL BIGINT,
	DEAL_AMOUNT DECIMAL(24,0) NOT NULL,
	DEAL_DISAMOUNT DECIMAL(24,2) NOT NULL,
	DEAL_DISRATE DECIMAL(10,3) NOT NULL,
	ENCOREDEAL_FLAG STRING,
	IS_EXTERNAL_DEAL STRING,
	DELIVERY_TYPE STRING,
	IS_FDIRECT_DELIVERY CHAR(1),
	ALWAYS_SALE CHAR(1),
	DEAL_FROM STRING NOT NULL,
	ADULT_TYPE STRING NOT NULL,
	USE_DIRECT_PIN STRING,
	ONE_MAN_MAX_COUNT INT NOT NULL,
	STOCK_COUNT BIGINT,
	ACTION_FROM STRING,
	CONTENTS_MAKING STRING,
	CD_STATUS_TYPE STRING,
	DEAL_DELIVERY_POLICY STRING,
	DEAL_DELIVERY_AMOUNT DECIMAL(24,0),
	DEAL_DELIVERY_IF_AMOUNT DECIMAL(18,0),
	USER_VIEW_YN STRING,
	LOAD_DT TIMESTAMP
);

CREATE TABLE tmon_netezza.mart.BI_D_MAIN_DEAL_INFO_WORK_02
(
	MAIN_DEAL_SRL BIGINT NOT NULL,
	EQUAL_PRICE_YN STRING,
	EQUAL_RATE_YN STRING,
	LOW_RATE_YN STRING,
	ONE_MAN_MAX_COUNT_OPTION BIGINT,
	MAX_COUNT BIGINT,
	LOAD_DT TIMESTAMP
);


CREATE TABLE tmon_netezza.mart.BI_D_MAIN_DEAL_INFO
(
	MAIN_DEAL_SRL BIGINT NOT NULL,
	DEAL_KIND STRING NOT NULL,
	MAIN_DEAL_NM STRING NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	TICKET_START_DATE DATE,
	TICKET_END_DATE DATE,
	STATUS_TYPE STRING,
	PARTNER_SRL BIGINT,
	CATEGORY_SRL BIGINT,
	DEAL_TYPE STRING,
	DELIVERY_SPOT STRING,
	TAG_SRL BIGINT,
	DEAL_AMOUNT DECIMAL(24,0),
	DEAL_DISAMOUNT DECIMAL(24,2),
	DEAL_DISRATE DECIMAL(10,3),
	ENCOREDEAL_FLAG CHAR(1),
	IS_EXTERNAL_DEAL STRING,
	DELIVERY_TYPE STRING,
	IS_FDIRECT_DELIVERY CHAR(1),
	ALWAYS_SALE CHAR(1),
	DEAL_FROM STRING,
	ADULT_TYPE STRING,
	USE_DIRECT_PIN STRING,
	ONE_MAN_MAX_COUNT BIGINT,
	STOCK_COUNT BIGINT,
	ACTION_FROM STRING,
	CONTENTS_MAKING STRING,
	CD_STATUS_TYPE STRING,
	EQUAL_PRICE_YN STRING,
	EQUAL_RATE_YN STRING,
	LOW_RATE_YN STRING,
	ONE_MAN_MAX_COUNT_OPTION BIGINT,
	MAX_COUNT BIGINT,
	DEAL_DELIVERY_POLICY STRING,
	DEAL_DELIVERY_AMOUNT DECIMAL(24,0),
	DEAL_DELIVERY_IF_AMOUNT DECIMAL(18,0),
	USER_VIEW_YN STRING,
	LOAD_DT TIMESTAMP
);
